version: "3.9"

services:
  web:
    image: php:8.2-apache
    container_name: php-web-bieb
    ports:
      - "3467:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-bieb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bieb
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-bieb
    depends_on:
      - db
    environment:
      PMA_HOST: db
    ports:
      - "3468:80"
